name: face
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  camera: ^0.11.2
  # firebase_ml_vision: ^0.12.0+3
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.11.0
  google_mlkit_face_detection: ^0.13.1
  image: ^4.5.4
  path_provider: ^2.1.5
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mobilefacenet.tflite